In [2]:
#Answer  1:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))



Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
#Answer 2 :

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#Answer 3 :

# Yes, there will be a difference. The elements in list_ are strings, whereas the elements in the new array_list will be integers.

array_list = np.array(object = list_, dtype = int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list after dtype change:")
for element in array_list:
    print(type(element))



Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list after dtype change:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
#Answer 4 :

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)



Shape of num_array: (2, 3)
Size of num_array: 6


In [6]:
#Answer 5 :

zeros_array = np.zeros((3, 3))
print("3x3 matrix containing zeros:\n", zeros_array)


3x3 matrix containing zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Answer 6 :

identity_matrix = np.eye(5)
print("5x5 identity matrix:\n", identity_matrix)


5x5 identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
